"""Generate backend/services/molecular_weights.py from the fetched PubChem data.

Generated rather than transcribed: hand-copying 112 numbers is exactly the kind
of step that introduces the errors this project keeps finding.
"""
import json
import sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

SCRATCH = ('C:/Users/nex88/AppData/Local/Temp/claude/'
           'C--Users-nex88-OneDrive-Desktop-psyc-medic-interaction-checker/'
           '09c0c047-d673-4573-9bd7-c7399df6a93f/scratchpad/')
OUT = ('C:/Users/nex88/OneDrive/Desktop/psyc medic interaction checker/'
       'neurotrace/backend/services/molecular_weights.py')

fetched = json.load(open(SCRATCH + 'mw_results.json'))
existing = json.load(open(SCRATCH + 'mw_existing.json'))

merged: dict[str, dict] = {}
for src in (existing, fetched['results']):
    for key, rec in src.items():
        merged[key.lower()] = rec

dextro = merged.get('dextroamphetamine', {}).get('mw')

# Special cases: a single molecular weight exists but needs explaining. Added
# explicitly so they resolve rather than falling through to a substitution.
merged['lithium'] = {
    'name': 'lithium', 'cid': 3028194, 'mw': 6.94, 'formula': 'Li',
}
merged['amphetamine salts'] = {
    'name': 'amphetamine salts', 'cid': merged['dextroamphetamine']['cid'],
    'mw': dextro, 'formula': merged['dextroamphetamine']['formula'],
}

HEADER = '''"""Molecular weights for every medication in the formulary.

Used to convert Ki and Km between uM and mg/L. Audit finding F-25: 79 of the
115 medications previously had no molecular weight and fell back to a guessed
350 g/mol, so their interaction magnitudes were computed against a number
nobody had checked.

Molecular weight is a fixed chemical constant rather than an uncertain
pharmacokinetic quantity, so unlike clearance or volume of distribution there
is no defensible reason to estimate it. Every value here is the free-base
(neutral) form retrieved from PubChem by name lookup on {date}, recorded with
its CID so it can be re-checked. Free base rather than salt is correct here
because plasma concentrations are reported as the active moiety.

The 36 values that were previously hard-coded were re-checked against PubChem
at the same time; all agreed to within 1%, so no stored value was wrong, only
unsourced.

Generated by scratchpad/gen_mw_module.py. Edit the generator, not this file.
"""
from __future__ import annotations

from services.provenance import Citation

PUBCHEM_RETRIEVED = '{date}'


'''.format(date='2026-08-15')

lines = [HEADER]

lines.append('MOLECULAR_WEIGHTS: dict[str, float] = {\n')
for key in sorted(merged):
    lines.append(f"    {key!r}: {merged[key]['mw']},\n")
lines.append('}\n\n')

lines.append('PUBCHEM_CID: dict[str, int] = {\n')
for key in sorted(merged):
    lines.append(f"    {key!r}: {merged[key]['cid']},\n")
lines.append('}\n\n')

lines.append('MOLECULAR_FORMULA: dict[str, str] = {\n')
for key in sorted(merged):
    lines.append(f"    {key!r}: {merged[key]['formula']!r},\n")
lines.append('}\n\n')

lines.append(f'''# Entries that are not a single chemical species. These are recorded rather
# than given a number, so the engine keeps flagging them instead of quietly
# using a value that does not mean anything.
UNRESOLVABLE: dict[str, str] = {{
    'ethinyl estradiol with norethindrone':
        'combination product; the two components have different molecular '
        'weights and no single value is meaningful',
}}

# Special cases where a single molecular weight exists but needs explaining.
SPECIAL_CASES: dict[str, str] = {{
    'lithium':
        'value is the lithium ion (6.94), not lithium carbonate (73.89). '
        'Lithium is renally cleared with no CYP involvement, so this weight is '
        'not used for any Ki or Km conversion. Note separately that lithium '
        'concentrations are reported clinically in mmol/L, not ng/mL, which the '
        'engine does not currently handle.',
    'amphetamine salts':
        'mixed amphetamine salts are dextroamphetamine and amphetamine as '
        'sulfate, saccharate and aspartate. The value is the amphetamine free '
        'base ({dextro}), the active moiety measured in plasma.',
}}


def molecular_weight(generic_name: str) -> float | None:
    """Molecular weight in g/mol, or None if not resolvable.

    Returning None is deliberate: callers must record a substitution rather
    than receive a silent default.
    """
    return MOLECULAR_WEIGHTS.get((generic_name or '').strip().lower())


def pubchem_citation(generic_name: str) -> Citation | None:
    """Traceable source for a molecular weight."""
    key = (generic_name or '').strip().lower()
    cid = PUBCHEM_CID.get(key)
    if cid is None:
        return None
    return Citation(
        source_db='PubChem CID', accession=str(cid),
        source_url=f'https://pubchem.ncbi.nlm.nih.gov/compound/{{cid}}',
        title=f'{{key}} ({{MOLECULAR_FORMULA.get(key, "")}})',
        verified=True,
    )
''')

open(OUT, 'w', encoding='utf-8').write(''.join(lines))
print('wrote', OUT)
print('entries:', len(merged))
print('unresolvable: 1 (ethinyl estradiol with norethindrone)')
print('special cases: 2 (lithium, amphetamine salts)')
